markdown: rdiscount
paginate: 5
exclude:  [ Gemfile, Gemfile.lock, Procfile, vendor, Rakefile]
permalink: pretty
highlighter: pygments
excerpt_separator: '<!-- more -->'
url: 'https://auth0.com'
baseurl: '/blog'
encoding: utf-8
only_first_p:
  show_read_more_link: true
  read_more_link_text: 'Read more'
stylus:
  compress: true
  path: ./css
values:
  is_post_index: false
gems:
  - jekyll-sitemap
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      related:
        - 2016-04-15-angularjs-authentication-screencast-series-part-1
        - 2016-04-21-facebook-account-kit-passwordless-authentication
        - 2016-02-03-getting-started-with-auth0-lock-series-implementing-lock

